### ISSUE TITLE
Share the trained embeddings?

### ISSUE THREAD

**Issue by zachmayer** [benathi/word2gm#2]
It would be useful to share your trained embeddings, so we don't have to train them ourselves!

**Comment by benathi** [comment]
Thank you for your suggestion. We will make the trained embeddings available soon!

**Comment by unvaiso** [comment]
Any news about this @benathi ?

**Comment by benathi** [comment]
Hi! I just added the link in README. The file is being uploaded right now and it should be available soon tonight. If you download right away it might be an incomplete file so wait about a hour or more to be sure. It should be about 470 MB.

**Comment by zachmayer** [comment]
I tried to download the file, and it's only ~50MB.  Maybe the upload stalled?

**Comment by zachmayer** [comment]
@benathi The link doesn't work now:
```
This site can’t be reached

35.161.153.223 refused to connect.
```

**Comment by benathi** [comment]
It's fixed and the link should work now. Please try again.

**Comment by zachmayer** [comment]
@benathi Downloading now.  Looks like ~452MB.  Thanks!

**Comment by zachmayer** [comment]
@benathi Got the file downloaded and unzipped.  There's 4 files in the folder:
```
- checkpoint
- model.ckpt-481392835.data-00000-of-00001
- model.ckpt-481392835.index
- model.ckpt-481392835.meta
- vocab.txt
```

How would I load the pre-trained embeddings back into python?

**Comment by benathi** [comment]
Please see README for more details.

**Comment by Frank-17** [comment]
The trained model for K=2 is not available any more.

Connecting to 35.161.153.223:6004... failed: Connection timed out.

Could you fix it, please?
