### ISSUE TITLE
ImportError: No module named models.embedding

### ISSUE THREAD

**Issue by unvaiso** [benathi/word2gm#3]
I ran the train_test8.sh and the following message popped up:
`Traceback (most recent call last):
  File "word2gm_trainer.py", line 27, in <module>
    from tensorflow.models.embedding import gen_word2vec as word2vec
ImportError: No module named models.embedding
`

Apparently it's related to the compilation of [tutorials](https://github.com/tensorflow/models/tree/master/tutorials) from the tensorflow models [repo](https://github.com/tensorflow/models). So I have tried recompiling  tensorflow from sources with the models in it, but in vain.

Any thoughts about this please ?

**Comment by benathi** [comment]
What version of Tensorflow are you using?

**Comment by unvaiso** [comment]
I am using the master version, the most recent. 1.1.0

**Comment by benathi** [comment]
This repo requires Tensorflow 0.11 or 0.12. It's not compatible with Tensorflow version 1.0 or 1.1 where they have removed the models.embedding module.

**Comment by unvaiso** [comment]
Thank you. I will try with that.
