### ISSUE TITLE
Can I train word2GM on very short expressions ?

### ISSUE THREAD

**Issue by unvaiso** [benathi/word2gm#4]

**Comment by benathi** [comment]
Can you elaborate on this? Do you mean training on a corpus which consists of only very short phrases/sentences? If that's what you mean, the answer is yes. Whether that would give high quality embeddings is not clear. I would assume that longer sentences give more contextual information and should yield better word embeddings quality.

**Comment by unvaiso** [comment]
Thank you,  that's what I wanted to know.
