### ISSUE TITLE
Projectutil missing

### ISSUE THREAD

**Issue by divyamsm** [benathi/word2gm#7]
From projectutil the code imports find_list_ckpts. But that module isn't made available or referred to.

**Comment by yujiakimoto** [comment]
You can find it in a previous commit [here](https://github.com/benathi/word2gm/blob/90a3f50cb66d4f863eed90913bc31dbdd8064fd4/projectutil.py)

**Comment by benathi** [comment]
Thank you. It was accidentally removed but I added it back.
